export const buyer_headlines = [
  'MIKÄ ON KYKY TODAY?',
  'KETKÄ OVAT SKILLERIT?',
  'MIKSI MINUN PITÄISI REKISTERÖITYÄ KÄYTTÄJÄKSI KYKY TODAY-ALUSTAAN?',
  'MITÄ OVAT KYKY TODAYN PÄÄTYÖLINJAT?',
  'MITEN ETSIN TYÖNTEKIJÄÄ/PALVELUA KYKY TODAY-SIVUSTOLLA?',
  'KUINKA VALITA SKILLERI?',
  'MITKÄ OVAT ALUSTAN KÄYTTÄMÄT MAKSUTAVAT?',
  'PITÄÄKÖ MINUN REKISTERÖITYÄ OSTAJAKSI?',
  'KUINKA LUON OSTAJA-PROFIILIN KYKY TODAY-ALUSTALLE?',
  'VOINKO MUUTTAA / PÄIVITTÄÄ OSTAJAN PROFIILIA?',
  'UNOHDIN SALASANANI. VOINKO NOLLATA SEN?',
  'MITÄ TIETOJA KYKY TODAY KERÄÄ?',
  'MISSÄ ON MINUN TILAUKSENI?',
  'VOIKO SKILLERIN KANSSA KOMMUNIKOIDA ENNEN KEIKKAA?',
  'VOINKO PERUUTTAA VARAUKSEN?',
  'MITÄ TAPAHTUU, JOS SKILLERI JÄTTÄÄ SAAPUMATTA?',
  'KUINKA ILMOITAN TYYTYMÄTTÖMYYDESTÄ SKILLERIN, HÄNEN TEKEMÄÄN TYÖHÖN TAI PALVELUUN?',
  'MITÄ TAPAHTUU, JOS SKILLERI VAHINGOITTAA OMAISUUTTANI?',
  'PITÄÄKÖ MINUN KIRJOITTAA ARVOSTELU KYKY -SOVELLUKSELLANI?',
  'VOINKO OLLA SEKÄ OSTAJA ETTÄ MYYJÄ KYKY TODAY-ALUSTALLA?'
];

export const buyer_texts = [
  'Kyky on sosiaalinen alusta, jossa freelancerit, yrittäjät, opiskelijat, ja harrastelijat voivat markkinoida taitojaan ja palveluitaan ostajille Suomessa tai muussa maassa.',
  'Skillerit ovat henkilöitä, jotka ovat kokopäivätyössä, osa-aikatyössä, työttöminä tai eläkkeellä, ketkä tekevät keikkoja, myyvät ja markkinoivat taitojansa, kykyjensä mukaan ostajille, jotka ovat rekisteröityneet Kyky Today-alustaan.',
  'Kyky on vallankumouksellinen sosiaalinen alusta, jonka avulla monet eri ammattialoille erikoistuneet kyvyt voivat lisätä näkyvyyttään potentiaalisille asiakkaille. Myymällä taitojaan verkossa sekä offline-tilassa Skillerit vastaavat työmarkkinoiden välittömiin tarpeisiin, tarjoamalla kustannustehokkaita ja joustavia palveluita.',
  'Kyky Today kattaa useita aloja ja ammatillisia taitoja. Pääkategoriat ovat: \nKoti & korjaukset - kodin korjaus- ja huoltotyöt; kierrätys; kausikohtaiset työt kuten lumen kolaus, puutarhatyöt ja maisemasuunnittelu. \nMuuto & Siivous - Siivous- ja muuttotyö. \nHoito & Hoiva - Lasten ja vanhusten hoito ja tuki; lemmikkien hoito; terveys valmennus; urheilu- ja kuntosalivalmentajat; kampaajat, meikkaajat ja muoti-ammattilaiset. \nLuovuus & IT - Valokuvaajat, graafiset suunnittelijat, sisällön tuottajat, sosiaalisen median ammattilaiset, artistit; ohjelmoijat, IT tuottajat, IT suunnittelijat, teknikot ja muut. \nOpetus & Valmennus - Opettajat ja tuutorit; elämäntapa valmentajat; kirjanpitäjät, bisnes asiantuntijat; laki, vero ja rahoitus ammattilaiset. \nViihde & Pitopalvelu - Kokit, pitopalvelut; tapahtumien järjestäjät ja viihdyttäjät.',
  'Siirry kotisivulla olevaan ’Hae’ palkkiin ja kirjoita hakusana. Voit helposti etsiä keikkaa tai taitoja kirjoittamalla mitä tahansa avainsanoja, jotka liittyvät tarvitsemaasi palveluun. \nToinen tapa on kategorian valitseminen pudotusvalikosta. \nVoit tarkentaa hakusi alueen, etäisyyden, hintaluokan, Skillerin kokemuksen perusteella tai kirjoittamalla henkilön / yrityksen nimen.',
  'Kun etsit työntekijää taitojen perusteella, saat listan freelancereista, heidän hinnoista, avoimesta kalenterista, käytettävyydesta, arvosteluista ja sijainnista. Klikkaamalla ‘VALITSE’ voit varata ammattitaitoisen Skillerin ja lisätä tarkentavia kysymyksiä kommenttikenttään. Lisäviestintää varten ostajat ja myyjät voivat kommunikoida sisäisen viestintäkanavan kautta Kyky Today-alustalla.',
  'KyKy Today-alusta tarjoaa suoran maksuyhteyden työntekijän ja ostajan välillä. Tällä hetkellä, vaihtoehdot ovat seuraavat: Stripe, Paypal ja tilisiirto.',
  'Sinun on rekisteröidyttävä ostajaksi vain, kun haluat ostaa palvelun. Huomaa, että rekisteröinti on ilmaista ja kestää muutaman minuutin.',
  'Voit rekisteröityä ostajaksi kotisivumme kautta rekisteröimällä sähköpostisi. Rekisteröinti ja tilin luominen Kyky today-alustalla on maksutonta. Kun olet rekisteröitynyt, saat vahvistussähköpostin. Klikkaa sähköpostiviestissä olevaa linkkiä aktivoidaksesi ostaja-profiilisi.',
  'Kyllä, voit muokata / päivittää profiiliasi milloin tahansa.',
  'Ole hyvä ja kirjoita sähköpostiosoitteesi ja napsauta kotisivulla “unohtunut salasana”-kohtaa. Lähetämme sinulle sähköpostia, jonka avulla voit vaihtaa salasanasi.',
  'Tarvitsemme ainoastaan sähköpostiosoitteesi ja nimesi, jos olet ostamassa palveluja. \nHuomaa, että Skilleri kysyy offline-tilassa sijaintiasi (osoite ja postinumero), koska hänen tarvitsee tavoittaa sinut tehtävän suorittamiseksi. Keskustelu hoidetaan foorumin käytettävissä olevan pikaviestivaihtoehdon kautta.',
  'Saat välittömästi sähköpostiin yhteenvedon tilauksesta, mistä löytyy myös viitenumero. Samalla, tilauksesi ilmestyy myös profiilissasi ‘ varaukseni ‘- välilehdelle. Varauksessasi näet yhteenvedon varaamastasi Skilleristä, varausajankohdasta, hinnasta, hänen suosimasta maksutavasta sekä muusta mahdollisesta lisätiedosta. Huomaa, että jos jokin ei ole selvää, voit lähettää pikaviestin järjestelmän kautta Skillerille tai ottaa yhteyttä Kyky- tukitiimiin saadaksesi lisätietoja tai päivityksiä.',
  'Kyllä. Voit käyttää sisäistä viestintäjärjestelmäämme milloin tahansa, jos Skilleri on sallinut yhteydenpidon ennen varauksen vahvistamista.',
  'Voit perua varauksen ongelmitta. Kuitenkin on tärkeä huomioida, että jotkut Skillerit saattavat veloittaa peruutusmaksun 14 päivän kuluessa. \nKannustamme sinua selvittämään asiat teidän Skillerinne kanssa ja sopimaan uudelleenjärjestelyistä ennen ajan peruutuksen hyväksymistä. Peruutus-painike on käytettävissä kohdassa ’varaukset.’',
  'Silloin ette maksa hänen palkkaansa. Jos Skilleri jättää saapumatta, eikä ilmoita sinulle etukäteen, hänestä voidaan ilmoittaa Kyky- tukitiimillemme sivustollamme olevan väärinkäyttäjäraportoinnin kautta.',
  'Jos et ole tyytyväinen Skillerin suorittamaan keikkaan tai palveluun, voit kertoa siitä yksityisviestillä tai jättäämällä arvostelun hänen profiilin alle. \nKehotamme sinua ratkaisemaan ongelman suoraan Skillerin kanssa. Emme puutu asiaan, ellet pyydä meiltä tukea ottamalla meihin yhteyttä ‘OTA YHTEYTTÄ ’- painikkeen kautta.',
  'Kiinteistön omistajat voivat pyytää Skillerista korvaamaan aiheuttamansa vahingot, sillä Skillerit ovat 100% vastuussa heidän toimistaan. Kannustamme Skilleria ottamaan vakuutuksen itselleen, sillä se on osoitus luotettavuudesta, ammattimaisuudesta ja taloudellisesta vastuusta. Suosittelemme, että omaa mielenrauhaasi varten valitset Skillerin, jolla on vakuutus',
  'Suosittelemme arvostelemaan Skillerin työtä, koska se auttaa ammattilaisia rakentamaan uskottavuutta ja se auttaa tulevia ostajia valitsemaan sopivan ammattilaisen heidän työlleen. Kun keikka on valmis, saat järjestelmältä sähköpostin, jossa pyydetään arvostelua. Huomaa, että palautteen antaminen on mahdollista 14 päivän ajan sekä ostajille että myyjille. \nArviointikriteerit – yhdestä (huonoimmasta) viiteen (parhaimpaan) tähdestä – ovat seuraavat: \nPalvelun laatu – mittaa palvelun laatua verrattuna ostajan odotuksiin. \nViestintä - mittaa viestinnän tehokkuutta ennen keikkaa ja sen aikana. Esim. Skilleri vastasi nopeasti tai on luotettava vastatessa ostajien kysymyksiin. \nAjanhallinta - mittaa työn organisoinnin ja suunnittelun prosessia varaus-ajan sisällä. \nSääntöjen kunnioitus - mittaa miten hyvin sääntöjä on noudatettu, ystävällisyys ja kohteliaisuus mukaan lukien.',
  'Kyllä voit. Voit olla sekä ostaja että myyjä. Vaihda vain ostamisesta myyntiin.'
];
